name: 'Enable GitHub Pull Reaquest Auto Merge Action'
description: 'Enables auto merge for GitHub Pull Request .'
author: 'Kenji Saito <ken-yo@mbr.nifty.com>'
branding:
  icon: 'terminal'
  color: 'yellow'
inputs:
  pull_request_number:
    description: number of Pull Request
  pull_request_id:
    description: ID of Pull Request
  github_token:
    required: true
  owner:
    description: repository owner
    required: true
  repository:
    description: target repository
    required: true
  merge_method:
    description: merge method. see [GitHub API Docs](https://docs.github.com/en/graphql/reference/enums#pullrequestmergemethod)
    required: false
runs:
  using: 'node12'
  main: 'dist/main.js'