name: 'Enable GitHub Pull Reaquest Auto Merge Action'
description: 'Enables auto merge for GitHub Pull Request .'
author: 'Kenji Saito <ken-yo@mbr.nifty.com>'
branding:
  icon: 'terminal'
  color: 'yellow'
inputs:
  pull_request_number:
    description: number of Pull Request
  github_token:
    required: false
    default: ${{ secrets.GITHUB_TOKEN }}
  owner:
    description: repository owner
    required: true
  repository:
    description: target repository
    required: true
  merge_method:
    description: merge method. see [GitHub API Docs](https://docs.github.com/en/graphql/reference/enums#pullrequestmergemethod)
    required: false
  with_approve:
    description: true if the Pull Request is approved. see [GitHub API Docs](https://docs.github.com/en/graphql/reference/mutations#submitpullrequestreview)
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
