packages:
  - .

onlyBuiltDependencies:
  - esbuild

autoInstallPeers: true
legacyPeerDeps: true
strictPeerDependencies: false

overrides:
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'

# one day
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
 - pnpm
