packages:
  - .

onlyBuiltDependencies:
  - esbuild

autoInstallPeers: true
legacyPeerDeps: true
strictPeerDependencies: false

# one day
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
 - pnpm

overrides:
  eslint@=9.39.0: 9.38.0
  '@eslint/js@=9.39.0': 9.38.0
