packages:
  - .

onlyBuiltDependencies:
  - esbuild

auto-install-peers: true
legacy-peer-deps: true
strict-peer-dependencies: false

# one day
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
 - pnpm
